// Acceptance tests. Each one builds the exact shape a behaviour is supposed to
// handle and asserts on the number that behaviour produces — never on text that
// also occurs in a header, which is how v0.1.0's suite let 14 of 20 one-line
// feature deletions pass.

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CLI = join(HERE, "..", "skills", "loadpath", "scripts", "loadpath.mjs");

const ENV = {
  ...process.env,
  GIT_AUTHOR_NAME: "A", GIT_AUTHOR_EMAIL: "a@e.com",
  GIT_COMMITTER_NAME: "A", GIT_COMMITTER_EMAIL: "a@e.com",
  GIT_CONFIG_GLOBAL: "/dev/null", GIT_CONFIG_SYSTEM: "/dev/null",
};

function repo() {
  const d = mkdtempSync(join(tmpdir(), "lp-"));
  return {
    dir: d,
    file(p, body = "x\n") { const f = join(d, p); mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, body); return f; },
    git(...a) { return execFileSync("git", ["-C", d, ...a], { encoding: "utf8", env: ENV, stdio: ["ignore", "pipe", "pipe"] }); },
    init(fmt) { this.git("init", "-q", "-b", "main", ...(fmt ? ["--object-format", fmt] : [])); return this; },
    commit(when, author) {
      this.git("add", "-A");
      execFileSync("git", ["-C", d, "-c", "commit.gpgsign=false", "commit", "-qm", "c"], {
        env: { ...ENV, GIT_AUTHOR_DATE: when, GIT_COMMITTER_DATE: when, ...(author ? { GIT_AUTHOR_NAME: author, GIT_COMMITTER_NAME: author } : {}) },
        stdio: ["ignore", "pipe", "pipe"],
      });
    },
    run(...args) {
      return execFileSync("node", [CLI, d, ...args], { encoding: "utf8", env: ENV, stdio: ["ignore", "pipe", "pipe"] });
    },
    clean() { rmSync(d, { recursive: true, force: true }); },
  };
}

const line = (out, needle) => out.split("\n").find((l) => l.includes(needle));
const nums = (s) => (s || "").match(/-?\d[\d,]*/g)?.map((x) => Number(x.replace(/,/g, ""))) ?? [];

// ── Inventory ────────────────────────────────────────────────────────────────

test("counts files and lines, and states the distribution", () => {
  const r = repo();
  try {
    for (let i = 0; i < 5; i++) r.file(`pkg/f${i}.go`, "x\n".repeat(10));
    r.file("pkg/big.go", "x\n".repeat(100));
    const out = r.run();
    assert.match(out, /^6 source files, 150 lines, 1 directories/m);
    assert.equal(nums(line(out, "lines per file"))[0], 10, "median must be the median, not the mean");
  } finally { r.clean(); }
});

test("generated and vendored files are excluded before anything else", () => {
  const r = repo();
  try {
    r.file("src/real.go", "x\n");
    r.file("src/api.pb.go", "x\n".repeat(500));
    r.file("src/marked.go", "// Code generated by tool. DO NOT EDIT.\nx\n");
    r.file("node_modules/dep/index.js", "x\n".repeat(999));
    r.file("vendor/lib/v.go", "x\n".repeat(999));
    const out = r.run();
    assert.match(out, /^1 source files/m);
  } finally { r.clean(); }
});

test("a symlinked directory is not followed", () => {
  const r = repo();
  try {
    r.file("a/one.go", "x\n");
    execFileSync("ln", ["-s", join(r.dir, "a"), join(r.dir, "b")]);
    assert.match(r.run(), /^1 source files/m);
  } finally { r.clean(); }
});

test("the test convention is inferred by vote, not assumed", () => {
  const r = repo();
  try {
    for (let i = 0; i < 4; i++) { r.file(`p/a${i}.go`); r.file(`p/a${i}_test.go`); }
    assert.match(r.run(), /tests\s+4 files by \*_test\.\*/);
  } finally { r.clean(); }
});

test("Java- and C#-style test names are recognised, not counted as implementation", () => {
  const r = repo();
  try {
    for (const n of ["FooTest", "BarTest", "BazTests"]) r.file(`p/${n}.java`);
    r.file("p/Real.java");
    assert.match(r.run(), /tests\s+3 files/);
  } finally { r.clean(); }
});

// ── Deviation ranking ────────────────────────────────────────────────────────

test("ranks by deviation from the repository's own median, and prints the ratio", () => {
  const r = repo();
  try {
    for (let d = 0; d < 5; d++) for (let i = 0; i < 2; i++) r.file(`small${d}/f${i}.go`);
    for (let i = 0; i < 20; i++) r.file(`wide/f${i}.go`);
    const out = r.run();
    const first = out.split("furthest from")[1].split("\n")[1];
    assert.ok(first.includes("wide"), `the outlier must rank first, got: ${first}`);
    assert.ok(/10×\s*median/.test(first), `must print the ratio against the median, got: ${first}`);
  } finally { r.clean(); }
});

// ── History ──────────────────────────────────────────────────────────────────

test("a path git must quote-escape is still counted", () => {
  const r = repo(); r.init();
  try {
    r.file("ascii/plain.go"); r.file("unicode/结算.go");
    r.commit("2024-01-01T00:00:00");
    for (let i = 0; i < 5; i++) {
      r.file("ascii/plain.go", `v${i}\n`); r.file("unicode/结算.go", `v${i}\n`);
      r.commit(`2024-0${i + 2}-01T00:00:00`);
    }
    const out = r.run("--since", "20.years");
    assert.ok(!/co-change\s+not measured/.test(out), "history must be available");
    assert.equal(nums(line(out, "co-change   "))[1], 2, "median breadth must be 2, not 1");
    assert.ok(/unicode/.test(out), "the non-ASCII directory must appear");
  } finally { r.clean(); }
});

test("a SHA-256 repository is read, not reported as empty", () => {
  const r = repo();
  try {
    try { r.init("sha256"); } catch { return; }          // old git: nothing to test
    r.file("a/x.go"); r.file("b/y.go"); r.commit("2024-01-01T00:00:00");
    for (let i = 0; i < 4; i++) { r.file("a/x.go", `${i}\n`); r.file("b/y.go", `${i}\n`); r.commit(`2024-0${i + 2}-01T00:00:00`); }
    assert.ok(!/history\s+not measured/.test(r.run("--since", "20.years")), "64-char object ids must parse");
  } finally { r.clean(); }
});

test("a shallow clone refuses to report history rather than fabricating it", () => {
  const src = repo(); src.init();
  const dst = mkdtempSync(join(tmpdir(), "lp-shallow-"));
  try {
    for (let i = 0; i < 6; i++) { src.file(`d${i % 3}/f.go`, `${i}\n`); src.commit(`2024-0${i + 1}-01T00:00:00`); }
    execFileSync("git", ["clone", "-q", "--depth", "1", "file://" + src.dir, dst], { env: ENV, stdio: ["ignore", "pipe", "pipe"] });
    const out = execFileSync("node", [CLI, dst, "--since", "20.years"], { encoding: "utf8", env: ENV, stdio: ["ignore", "pipe", "pipe"] });
    assert.match(out, /history\s+not measured — shallow clone/);
  } finally { src.clean(); rmSync(dst, { recursive: true, force: true }); }
});

test("an unparseable --since is refused instead of silently emptying the window", () => {
  const r = repo(); r.init();
  try {
    r.file("a/x.go"); r.commit("2024-01-01T00:00:00");
    assert.match(r.run("--since", "banana"), /not a date git understands/);
  } finally { r.clean(); }
});

test("history counts directories that still exist, never more", () => {
  const r = repo(); r.init();
  try {
    r.file("gone/x.go"); r.file("stays/y.go"); r.commit("2024-01-01T00:00:00");
    rmSync(join(r.dir, "gone"), { recursive: true });
    r.file("stays/y.go", "2\n"); r.commit("2024-02-01T00:00:00");
    const out = r.run("--since", "20.years");
    const [active, total] = nums(line(out, "activity"));
    assert.equal(total, 1, "a deleted directory must not inflate the count");
    assert.ok(active <= total);
  } finally { r.clean(); }
});

// ── Commit share ─────────────────────────────────────────────────────────────

test("commit share is the top author's fraction, beside the count", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 30; i++) r.file(`p/f${i}.go`);
    r.commit("2024-01-01T00:00:00", "Ann");
    for (let i = 0; i < 3; i++) { r.file("p/f0.go", `${i}\n`); r.commit(`2024-0${i + 2}-01T00:00:00`, "Ann"); }
    r.file("p/f0.go", "z\n"); r.commit("2024-06-01T00:00:00", "Bob");
    // One directory has no deviation from a median it defines, so the share
    // is read from the structure table rather than the outlier section.
    const row = r.run("--since", "20.years", "--structure").split("\n").find((l) => /%\/\d+a/.test(l));
    assert.ok(row, "the structure table must carry the share");
    const share = Number(row.match(/(\d+)%\//)[1]);
    assert.ok(share >= 75 && share < 85, `4 of 5 commits by one author is 80%, got ${share}%`);
    assert.ok(/\b5c\b/.test(row), "the raw count must stay beside the ratio");
  } finally { r.clean(); }
});

// ── Co-change ────────────────────────────────────────────────────────────────

test("one commit is one vote, split across the pairs it implies", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 8; i++) r.file(`w${i}/f.go`);
    r.commit("2020-01-01T00:00:00");
    for (let i = 0; i < 8; i++) { r.file(`w${i}/f.go`, "edit\n"); }
    r.commit("2020-02-01T00:00:00");
    for (let i = 0; i < 6; i++) { r.file("a/f.go", `${i}\n`); r.file("b/f.go", `${i}\n`); r.commit(`2021-0${i + 1}-01T00:00:00`); }
    const out = r.run("--since", "20.years");
    const rows = out.split("\n").filter((l) => / \+ /.test(l) && /%/.test(l));
    assert.ok(rows.length, "pairs must be reported");
    assert.ok(/\ba \+ b\b/.test(rows[0]), `the repeated narrow pair must outrank a wide sweep, got: ${rows[0]}`);
  } finally { r.clean(); }
});

test("commits wider than the cap are excluded and the count is disclosed", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 12; i++) r.file(`d${i}/f.go`);
    r.commit("2020-01-01T00:00:00");
    for (let i = 0; i < 12; i++) r.file(`d${i}/f.go`, "e\n");
    r.commit("2020-02-01T00:00:00");
    const out = r.run("--since", "20.years", "--cap", "4");
    assert.match(out, /2 commits touched more than the breadth cap/);
  } finally { r.clean(); }
});

test("each pair carries its per-window profile and its min and max", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 6; i++) { r.file("a/f.go", `${i}\n`); r.file("b/f.go", `${i}\n`); r.commit(`2020-0${i + 1}-01T00:00:00`); }
    const row = line(r.run("--since", "20.years", "--windows", "4"), " + ");
    const prof = row.match(/\[([^\]]*)\]/);
    assert.ok(prof && /\d/.test(prof[1]), "the window profile must carry numbers");
    assert.ok(/min \d/.test(row) && /max \d/.test(row), "an aggregate ships with its spread");
    assert.match(r.run("--since", "20.years", "--windows", "4"), /4 equal time windows/);
  } finally { r.clean(); }
});

test("no verdict word is ever emitted", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 30; i++) r.file(`p/f${i}.go`, "x\n".repeat(900));
    r.commit("2024-01-01T00:00:00");
    for (let i = 0; i < 6; i++) { r.file("a/f.go", `${i}\n`); r.file("b/f.go", `${i}\n`); r.commit(`2024-0${i + 2}-01T00:00:00`); }
    const out = r.run("--since", "20.years");
    for (const w of ["god file", "rising", "at-creation", "fading", "violation", "smell", "problem", "should be split"]) {
      assert.ok(!out.toLowerCase().includes(w), `verdict word leaked: ${w}`);
    }
  } finally { r.clean(); }
});

// ── Relocations ──────────────────────────────────────────────────────────────

test("a directory rename is reported as a relocation", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 5; i++) r.file(`old/f${i}.go`, `body ${i}\n`.repeat(20));
    r.commit("2024-01-01T00:00:00");
    r.git("mv", "old", "new");
    r.commit("2024-02-01T00:00:00");
    const out = r.run("--since", "20.years");
    assert.match(out, /relocations/);
    assert.ok(/old → new/.test(out), "the move must name both sides");
  } finally { r.clean(); }
});

test("a rename inside one directory is not a relocation", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 5; i++) r.file(`p/f${i}.go`, `body ${i}\n`.repeat(20));
    r.commit("2024-01-01T00:00:00");
    for (let i = 0; i < 5; i++) r.git("mv", `p/f${i}.go`, `p/g${i}.go`);
    r.commit("2024-02-01T00:00:00");
    assert.ok(!/→/.test(r.run("--since", "20.years")), "no directory moved");
  } finally { r.clean(); }
});

// ── Dependencies: the quarantine ─────────────────────────────────────────────

test("with no applicable analyzer, dependencies are not measured — never zero", () => {
  const r = repo();
  try {
    r.file("a/x.rb", "require 'b'\n"); r.file("b/y.rb", "require 'a'\n");
    const l = line(r.run(), "dependencies");
    assert.match(l, /not measured/);
    assert.ok(!/0 edges/.test(l), "an unmeasured graph must never render as an empty one");
  } finally { r.clean(); }
});

test("Go edges come from go list and the component count matches", () => {
  const r = repo();
  try {
    try { execFileSync("go", ["version"], { stdio: "ignore" }); } catch { return; }
    r.file("go.mod", "module example.com/m\n\ngo 1.21\n");
    r.file("alpha/a.go", 'package alpha\n\nimport _ "example.com/m/beta"\n');
    r.file("beta/b.go", "package beta\n");
    const l = line(r.run(), "dependencies");
    assert.match(l, /go list/);
    assert.ok(/\b1 edges?\b/.test(l), `expected one edge, got: ${l}`);
    assert.match(r.run(), /0 mutually entangled group/);
  } finally { r.clean(); }
});

test("a real Go cycle is impossible, and a .csproj cycle is found", () => {
  const r = repo();
  try {
    r.file("A/A.csproj", '<Project><ItemGroup><ProjectReference Include="../B/B.csproj" /></ItemGroup></Project>');
    r.file("A/a.cs", "class A {}");
    r.file("B/B.csproj", '<Project><ItemGroup><ProjectReference Include="../A/A.csproj" /></ItemGroup></Project>');
    r.file("B/b.cs", "class B {}");
    const out = r.run("--structure");
    assert.match(out, /ProjectReference/);
    assert.match(out, /1 mutually entangled group/);
    assert.match(out, /entangled: 2 projects/);
  } finally { r.clean(); }
});

// ── Scope and budget ─────────────────────────────────────────────────────────

test("scanning a subdirectory keeps every path repository-relative", () => {
  const r = repo(); r.init();
  try {
    r.file("sub/a/x.go"); r.file("other/b/y.go");
    r.commit("2024-01-01T00:00:00");
    const out = execFileSync("node", [CLI, join(r.dir, "sub"), "--since", "20.years"], { encoding: "utf8", env: ENV, stdio: ["ignore", "pipe", "pipe"] });
    assert.match(out, /paths are repository-relative/);
    // The leak the scope note promised not to have: history and dependencies
    // must be scoped too, or the reader is shown directories the tool said it
    // was not scanning.
    assert.ok(!/other\/b/.test(out), `a directory outside the scope leaked in:\n${out}`);
    assert.match(out, /^1 source files/m, "only the scoped subtree is counted");
    const h = line(out, "history     ");
    assert.ok(/1 commits/.test(h), `history must be scoped too, got: ${h}`);
  } finally { r.clean(); }
});

test("the structure table honours its budget", () => {
  const r = repo();
  try {
    for (let d = 0; d < 200; d++) r.file(`d${d}/f.go`, "x\n".repeat(d + 1));
    const small = r.run("--structure", "--budget", "300");
    const large = r.run("--structure", "--budget", "3000");
    assert.ok(small.length < large.length, "a smaller budget must produce less");
    assert.match(small, /directories not shown/);
  } finally { r.clean(); }
});

test("--dir gives one subtree file by file", () => {
  const r = repo();
  try {
    r.file("keep/a.go", "x\n".repeat(30)); r.file("keep/b.go", "x\n");
    r.file("elsewhere/c.go", "x\n");
    const out = r.run("--dir", "keep");
    assert.ok(/keep\/a\.go/.test(out) && /keep\/b\.go/.test(out));
    assert.ok(!/elsewhere/.test(out), "only the named subtree");
  } finally { r.clean(); }
});

// ── Robustness ───────────────────────────────────────────────────────────────

test("an empty directory says so rather than failing", () => {
  const r = repo();
  try { assert.match(r.run(), /no source files found/); } finally { r.clean(); }
});

test("a repository with no git history still reports the filesystem facts", () => {
  const r = repo();
  try {
    r.file("p/a.go", "x\n");
    const out = r.run();
    assert.match(out, /^1 source files/m);
    assert.match(out, /history\s+not measured/);
  } finally { r.clean(); }
});

test("binary and unreadable files do not crash the scan", () => {
  const r = repo();
  try {
    writeFileSync(join(r.dir, "blob.go"), Buffer.from([0, 1, 2, 3, 0, 255, 10]));
    r.file("p/ok.go", "x\n");
    assert.match(r.run(), /source files/);
  } finally { r.clean(); }
});

test("the repository is never modified by a scan", () => {
  const r = repo(); r.init();
  try {
    r.file("go.mod", "module example.com/m\n\ngo 1.21\n");
    r.file("p/a.go", "package p\n");
    r.commit("2024-01-01T00:00:00");
    const before = r.git("status", "--porcelain") + r.git("rev-parse", "HEAD");
    r.run("--since", "20.years", "--structure");
    assert.equal(r.git("status", "--porcelain") + r.git("rev-parse", "HEAD"), before);
  } finally { r.clean(); }
});

test("weight spreads across the windows it was given", () => {
  const r = repo(); r.init();
  try {
    // Two bursts far apart. Collapsing the windows would put everything in one.
    for (let i = 0; i < 3; i++) { r.file("a/f.go", `${i}\n`); r.file("b/f.go", `${i}\n`); r.commit(`2020-0${i + 1}-01T00:00:00`); }
    for (let i = 0; i < 3; i++) { r.file("a/f.go", `l${i}\n`); r.file("b/f.go", `l${i}\n`); r.commit(`2024-0${i + 1}-01T00:00:00`); }
    const row = line(r.run("--since", "20.years", "--windows", "4"), " + ");
    const cells = row.match(/\[([^\]]*)\]/)[1].trim().split(/\s+/).map(Number);
    assert.equal(cells.length, 4);
    assert.ok(cells.filter((c) => c > 0).length >= 2, `weight must land in more than one window, got ${cells}`);
  } finally { r.clean(); }
});

test("a commit that only adds files weighs less than one that edits", () => {
  const bulk = repo(); bulk.init();
  const edit = repo(); edit.init();
  try {
    // Same pair, same number of commits. In one repo every commit only adds
    // files, which is creation rather than coupling; in the other they edit.
    for (let i = 0; i < 5; i++) {
      bulk.file(`a/f${i}.go`, "x\n"); bulk.file(`b/f${i}.go`, "x\n");
      bulk.commit(`2020-0${i + 1}-01T00:00:00`);
    }
    edit.file("a/f.go", "x\n"); edit.file("b/f.go", "x\n");
    edit.commit("2020-01-01T00:00:00");
    for (let i = 0; i < 4; i++) {
      edit.file("a/f.go", `${i}\n`); edit.file("b/f.go", `${i}\n`);
      edit.commit(`2020-0${i + 2}-01T00:00:00`);
    }
    const share = (r) => {
      const l = line(r.run("--since", "20.years"), "a + b");
      return l ? Number(l.match(/(\d+)%/)[1]) : 0;
    };
    const e = share(edit), b = share(bulk);
    assert.ok(e > b + 20, `an edit must weigh clearly more than a bulk creation, got edit ${e}% vs bulk ${b}%`);
  } finally { bulk.clean(); edit.clean(); }
});

test("the major-author count applies its stated share threshold", () => {
  const r = repo(); r.init();
  try {
    r.file("p/f.go"); r.commit("2024-01-01T00:00:00", "Ann");
    // Ann 18, Bob 2: Bob clears 5% of 20, so two authors are major.
    for (let i = 0; i < 17; i++) { r.file("p/f.go", `a${i}\n`); r.commit("2024-02-01T00:00:00", "Ann"); }
    for (let i = 0; i < 2; i++) { r.file("p/f.go", `b${i}\n`); r.commit("2024-03-01T00:00:00", "Bob"); }
    const row = r.run("--since", "20.years", "--structure").split("\n").find((l) => /%\/\d+a/.test(l) && / p$/.test(l));
    assert.ok(/\d+%\/2a/.test(row), `two authors clear 5%, got: ${row}`);

    const s2 = repo(); s2.init();
    try {
      s2.file("p/f.go"); s2.commit("2024-01-01T00:00:00", "Ann");
      // Ann 39, Bob 1: Bob is 2.5%, below the threshold, so only one is major.
      for (let i = 0; i < 38; i++) { s2.file("p/f.go", `a${i}\n`); s2.commit("2024-02-01T00:00:00", "Ann"); }
      s2.file("p/f.go", "b\n"); s2.commit("2024-03-01T00:00:00", "Bob");
      const row2 = s2.run("--since", "20.years", "--structure").split("\n").find((l) => /%\/\d+a/.test(l) && / p$/.test(l));
      assert.ok(/\d+%\/1a/.test(row2), `only one author clears 5%, got: ${row2}`);
    } finally { s2.clean(); }
  } finally { r.clean(); }
});

test("an analyzer that resolves no edges reports not measured, not zero", () => {
  const r = repo();
  try {
    try { execFileSync("go", ["version"], { stdio: "ignore" }); } catch { return; }
    // Two real Go packages that do not import each other.
    r.file("go.mod", "module example.com/m\n\ngo 1.21\n");
    r.file("alpha/a.go", "package alpha\n");
    r.file("beta/b.go", "package beta\n");
    const l = line(r.run(), "dependencies");
    assert.match(l, /not measured/);
    assert.ok(!/\b0 edges\b/.test(l), "no edges resolved is not the same as no dependencies");
  } finally { r.clean(); }
});

test("a single rename is not yet a relocation", () => {
  const r = repo(); r.init();
  try {
    for (let i = 0; i < 5; i++) r.file(`old/f${i}.go`, `body ${i}\n`.repeat(20));
    r.file("solo/one.go", "solo\n".repeat(20));
    r.commit("2024-01-01T00:00:00");
    r.git("mv", "solo/one.go", "elsewhere.go");     // one file: not a pattern
    r.commit("2024-02-01T00:00:00");
    const out = r.run("--since", "20.years");
    assert.ok(!/solo →/.test(out), `one moved file is not a relocation:\n${out}`);
  } finally { r.clean(); }
});

test("the active and dormant counts add up to the directories that exist", () => {
  const r = repo(); r.init();
  try {
    r.file("gone1/x.go"); r.file("gone2/x.go"); r.file("stays/y.go");
    r.commit("2024-01-01T00:00:00");
    rmSync(join(r.dir, "gone1"), { recursive: true });
    rmSync(join(r.dir, "gone2"), { recursive: true });
    r.file("stays/y.go", "2\n");
    r.commit("2024-02-01T00:00:00");
    const l = line(r.run("--since", "20.years"), "activity");
    const m = l.match(/(\d+) of (\d+) directories touched in the last \d+ days, (\d+) not/);
    assert.ok(m, `unexpected activity line: ${l}`);
    const [active, total, dormant] = [Number(m[1]), Number(m[2]), Number(m[3])];
    assert.equal(total, 1, "only one directory still exists");
    assert.equal(active + dormant, total, `active ${active} + dormant ${dormant} must equal ${total}`);
  } finally { r.clean(); }
});

test("a repository reached through a symlinked path is still scanned", () => {
  // Not an OS quirk: build the symlink explicitly, so the case is exercised
  // wherever the suite runs rather than only where /tmp happens to be one.
  const r = repo(); r.init();
  const link = join(tmpdir(), `lp-link-${process.pid}-${Date.now()}`);
  try {
    r.file("p/a.go", "x\n"); r.commit("2024-01-01T00:00:00");
    execFileSync("ln", ["-s", r.dir, link]);
    const out = execFileSync("node", [CLI, link, "--since", "20.years"], { encoding: "utf8", env: ENV, stdio: ["ignore", "pipe", "pipe"] });
    assert.match(out, /^1 source files/m, "a symlinked path must resolve to the same repository, not to a subdirectory of it");
    assert.ok(!/paths are repository-relative/.test(out), "the repository root reached by a symlink is still the root");
  } finally { rmSync(link, { force: true }); r.clean(); }
});

test("a graph covering a sliver of the tree is not measured", () => {
  const r = repo();
  try {
    // Three trivial C# projects among sixty directories: an analyzer runs and
    // resolves a real graph, but it covers too little to read as the tree's.
    for (let i = 0; i < 60; i++) r.file(`spread/d${i}/f${i}.cs`, "class X {}");
    for (const n of ["A", "B", "C"]) {
      r.file(`${n}/${n}.csproj`, '<Project><ItemGroup><ProjectReference Include="../A/A.csproj" /></ItemGroup></Project>');
      r.file(`${n}/${n.toLowerCase()}.cs`, `class ${n} {}`);
    }
    const l = line(r.run(), "dependencies");
    assert.match(l, /not measured/, `a sliver graph must not read as measured: ${l}`);
    assert.ok(/%\)/.test(l), "the coverage it did reach must be stated");
  } finally { r.clean(); }
});

test("an acyclic result is scoped to what the analyzer saw, not to the tree", () => {
  const r = repo();
  try {
    try { execFileSync("go", ["version"], { stdio: "ignore" }); } catch { return; }
    r.file("go.mod", "module example.com/m\n\ngo 1.21\n");
    r.file("alpha/a.go", 'package alpha\n\nimport _ "example.com/m/beta"\n');
    r.file("beta/b.go", "package beta\n");
    const out = r.run("--structure");
    assert.ok(!/graph is acyclic/.test(out), "a clean verdict must not come from the inexact module");
    assert.match(out, /no group found in the \d+ packages/, "say what was searched, not what is true");
  } finally { r.clean(); }
});

test("history unavailable renders as a mark, never as a blank under a count header", () => {
  const r = repo();
  try {
    for (let i = 0; i < 4; i++) r.file(`p${i}/a.go`, "x\n");
    const out = r.run("--structure");
    assert.match(out, /history not measured/, "the header must say the column is unmeasured");
    const row = out.split("\n").find((l) => /\bp0$/.test(l));
    assert.ok(row && /\?/.test(row), `a cell must carry a mark, not a blank: ${row}`);
  } finally { r.clean(); }
});

test("a flat distribution says so instead of presenting insertion order as outliers", () => {
  const r = repo();
  try {
    for (let i = 0; i < 20; i++) r.file(`d${i}/f.go`, "x\n");
    const out = r.run();
    assert.match(out, /the distribution is flat/);
    assert.ok(!/furthest from/.test(out), "there is nothing furthest when everything is equal");
  } finally { r.clean(); }
});

test("a module in a subdirectory is measured, wherever .git sits", () => {
  const r = repo(); r.init();
  try {
    try { execFileSync("go", ["version"], { stdio: "ignore" }); } catch { return; }
    r.file("svc/go.mod", "module example.com/svc\n\ngo 1.21\n");
    r.file("svc/alpha/a.go", 'package alpha\n\nimport _ "example.com/svc/beta"\n');
    r.file("svc/beta/b.go", "package beta\n");
    r.commit("2024-01-01T00:00:00");
    const l = line(r.run("--since", "20.years"), "dependencies");
    assert.match(l, /go list/, `a nested module must still be analysed: ${l}`);
  } finally { r.clean(); }
});

test("an unreadable file does not enter the inventory as zero lines", () => {
  const r = repo();
  try {
    r.file("p/good.go", "x\n".repeat(10));
    const bad = r.file("p/bad.go", "x\n".repeat(10));
    execFileSync("chmod", ["000", bad]);
    const out = r.run();
    assert.match(out, /^1 source files/m, "the unreadable file leaves the inventory");
    assert.equal(nums(line(out, "lines per file"))[0], 10, "it must not drag the median to zero");
    execFileSync("chmod", ["644", bad]);
  } finally { r.clean(); }
});
